# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6bec84ea8fa64995348dbcc38187e172749c10ec37be28ff1a34d7d1816e350bf0f047e4b09c58a0543308d8f6bebf3f73cb0590278604cf646f7a508128801

test:
  secret_key_base: a213be1d0f339f13a89bbde8885e2ef5a821a60262998354891cbba88bd5b01f4b9b99584c99605337fce7b132a4c013977ddb69974dd2b0c90b131c949074a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
